import { and, asc, eq } from 'drizzle-orm'
import { getDb } from '@/lib/db'
import {
  generationPlanJudgments,
  generationPlanOverrides,
  generationProposals,
  generationSessions,
  generationTurns,
  reportVariants,
  type GenerationPlanOverride,
} from '@/lib/db/schema'
import { normalizeCarryForwardSnapshot } from './carry-forward-snapshot'
import {
  summarizePlanOverrides,
  buildBaselineItemsMap,
  type PlanOverrideAction,
} from './plan'
import { GenerationServiceError, error } from './service'

export { GenerationServiceError }

function cleanOverrideText(value: string): string {
  return value.replace(/^\s*(?:[-*+]\s+|\d+[.)]\s+)/, '').replace(/\s+/g, ' ').trim().slice(0, 500)
}

function overrideItemSource(input: {
  itemId: string
  snapshotCandidateIds: Set<string>
  existing: GenerationPlanOverride[]
}): 'carry-forward' | 'this-week-new' | 'baseline' | null {
  if (input.snapshotCandidateIds.has(input.itemId)) return 'carry-forward'
  // Baseline items use the 'baseline-{hash}' format generated by generateBaselineItemId().
  // This prefix check is the established convention for identifying baseline items.
  if (input.itemId.startsWith('baseline-')) return 'baseline'
  return input.existing.find((record) => record.itemId === input.itemId)?.source ?? null
}

export function persistUncertainPlanJudgments(sessionId: number, turnId: number): void {
  const db = getDb()
  const session = db.select().from(generationSessions).where(eq(generationSessions.id, sessionId)).get()
  if (!session) return
  const snapshot = normalizeCarryForwardSnapshot(session.carryForwardSnapshot)
  if (snapshot.candidates.length === 0) return
  const existing = db.select({ candidateId: generationPlanJudgments.candidateId })
    .from(generationPlanJudgments).where(eq(generationPlanJudgments.sessionId, sessionId)).all()
  const seen = new Set(existing.map((item) => item.candidateId))
  const now = new Date()
  for (const candidate of snapshot.candidates) {
    if (seen.has(candidate.candidateId)) continue
    db.insert(generationPlanJudgments).values({
      sessionId,
      candidateId: candidate.candidateId,
      judgment: 'uncertain',
      reason: '本轮超时、失败或部分返回，未能可靠判断；默认不自动结转。',
      remainingAction: null,
      turnId,
      createdAt: now,
    }).run()
  }
}

export async function appendPlanOverride(input: {
  reportId: number
  sessionId: number
  action: PlanOverrideAction
  itemId?: string
  text?: string
}) {
  const db = getDb()

  // Pre-fetch session to build baseline items map outside transaction
  const preSession = db.select().from(generationSessions).where(
    and(eq(generationSessions.id, input.sessionId), eq(generationSessions.reportId, input.reportId)),
  ).get()
  if (!preSession) error('Generation session not found', 'SESSION_NOT_FOUND', 404)

  // Build baseline items map outside transaction
  const baselineItemsMap = buildBaselineItemsMap(preSession.baselineFinalContent)

  return db.transaction((tx) => {
    const session = tx.select().from(generationSessions).where(
      and(eq(generationSessions.id, input.sessionId), eq(generationSessions.reportId, input.reportId)),
    ).get()
    if (!session) error('Generation session not found', 'SESSION_NOT_FOUND', 404)
    if (session.status !== 'active') error('Session is archived', 'SESSION_ARCHIVED', 409)
    const currentVariant = tx.select().from(reportVariants).where(eq(reportVariants.id, session.reportVariantId)).get()
    if (!currentVariant || currentVariant.sourceRevision !== session.sourceRevision) {
      error('The source draft has changed; start a new session', 'SOURCE_REVISION_CONFLICT', 409)
    }
    const activeTurn = tx.select().from(generationTurns).where(
      and(eq(generationTurns.sessionId, session.id), eq(generationTurns.status, 'working')),
    ).get()
    if (activeTurn) error('AI is still generating; wait for the current turn to finish', 'TURN_IN_PROGRESS', 409)

    const snapshot = normalizeCarryForwardSnapshot(session.carryForwardSnapshot)
    const existing = tx.select().from(generationPlanOverrides)
      .where(eq(generationPlanOverrides.sessionId, session.id)).orderBy(asc(generationPlanOverrides.id)).all()
    const snapshotCandidateIds = new Set(snapshot.candidates.map((candidate) => candidate.candidateId))
    const text = typeof input.text === 'string' ? cleanOverrideText(input.text) : ''
    let itemId = input.itemId?.trim() ?? ''
    let source: 'carry-forward' | 'this-week-new' | 'baseline'
    const createdNewItem = !itemId

    if (createdNewItem) {
      if (input.action !== 'keep' || !text) {
        error('A new plan item requires keep with non-empty text', 'INVALID_PLAN_OVERRIDE', 400)
      }
      const nextItemNumber = existing.reduce((maximum, record) => {
        const match = record.itemId.match(/^session-item-(\d+)$/)
        return match ? Math.max(maximum, Number.parseInt(match[1], 10)) : maximum
      }, 0) + 1
      itemId = `session-item-${nextItemNumber}`
      source = 'this-week-new'
    } else {
      const resolvedSource = overrideItemSource({ itemId, snapshotCandidateIds, existing })
      if (!resolvedSource) error('Plan item not found in this session', 'PLAN_ITEM_NOT_FOUND', 404)
      source = resolvedSource
    }

    const itemHistory = existing.filter((record) => record.itemId === itemId)
    const latest = itemHistory.at(-1)
    if (input.action === 'rewrite' && !text) {
      error('Rewrite requires non-empty replacement text', 'INVALID_PLAN_OVERRIDE', 400)
    }
    if (input.action === 're-add' && latest?.action !== 'drop') {
      error('Only a dropped plan item can be re-added', 'PLAN_ITEM_NOT_DROPPED', 409)
    }
    if (latest?.action === 'drop' && input.action !== 'drop' && input.action !== 're-add') {
      error('Re-add the dropped plan item before applying another change', 'PLAN_ITEM_READD_REQUIRED', 409)
    }

    const now = new Date()
    const record = tx.insert(generationPlanOverrides).values({
      sessionId: session.id,
      itemId,
      action: input.action,
      replacementText: input.action === 'rewrite' || createdNewItem ? text : null,
      source,
      createdAt: now,
    }).returning().get()
    tx.update(generationProposals).set({ status: 'superseded' }).where(
      and(eq(generationProposals.sessionId, session.id), eq(generationProposals.status, 'pending')),
    ).run()
    tx.update(generationSessions).set({ updatedAt: now }).where(eq(generationSessions.id, session.id)).run()
    const records = [...existing, record]

    return {
      ...record,
      state: summarizePlanOverrides(snapshot, records, baselineItemsMap).find((item) => item.itemId === itemId) ?? null,
    }
  })
}
